# -*- coding: utf-8 -*-
"""IMERSION_DATOS_AULA_1 _TAREA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18WG5cpKGByM8rZpj_CSibrvEVjYBFxGy

Mi Primer Encuantro En Inmersion De Datos : TAREA
"""

from google.colab import drive

drive.mount('/content/drive')

import pandas as pd

inmuebles = pd.read_csv("/content/drive/MyDrive/inmuebles_bogota (1).csv")
inmuebles

"""Promedio de área de todos los inmuebles en los barrios"""

inmuebles[["Barrio","Área"]].groupby(["Barrio"]).mean().sort_values(by=["Área"], ascending=False)

"""Promedio de área de todos los inmuebles en los barrios. El Top 10"""

inmuebles[["Barrio","Área"]].groupby(["Barrio"]).mean().sort_values(by=["Área"], ascending=False).head(10)

"""Grafico del promedio de área de todos los inmuebles en los barrios. El Top 10"""

inmuebles[["Barrio","Área"]].groupby(["Barrio"]).mean().sort_values(by=["Área"], ascending=False).head(10).plot(kind='bar')

import numpy as np

inmuebles["ValorNumero"] = inmuebles["Valor"].str.replace("[^\d]", "", regex=True).astype(np.int64)

inmuebles.info()

inmuebles["Tipo"].value_counts()

"""Casa mas Cara"""

inmuebles[inmuebles["Tipo"]=="Casa"]["ValorNumero"].max()

inmuebles[inmuebles["Tipo"]=="Casa"][inmuebles[inmuebles["Tipo"]=="Casa"]["ValorNumero"]==inmuebles[inmuebles["Tipo"]=="Casa"]["ValorNumero"].max()]

"""Casa mas barata"""

inmuebles[inmuebles["Tipo"]=="Casa"]["ValorNumero"].min()

inmuebles[inmuebles["Tipo"]=="Casa"][inmuebles[inmuebles["Tipo"]=="Casa"]["ValorNumero"]==inmuebles[inmuebles["Tipo"]=="Casa"]["ValorNumero"].min()]

"""Apartamento mas caro"""

inmuebles[inmuebles["Tipo"]=="Apartamento"]["ValorNumero"].max()

inmuebles[inmuebles["Tipo"]=="Apartamento"][inmuebles[inmuebles["Tipo"]=="Apartamento"]["ValorNumero"]==inmuebles[inmuebles["Tipo"]=="Apartamento"]["ValorNumero"].max()]

"""Apartamento mas barato"""

inmuebles[inmuebles["Tipo"]=="Apartamento"]["ValorNumero"].min()

inmuebles[inmuebles["Tipo"]=="Apartamento"][inmuebles[inmuebles["Tipo"]=="Apartamento"]["ValorNumero"]==inmuebles[inmuebles["Tipo"]=="Apartamento"]["ValorNumero"].min()]

"""Casa con menos baños"""

inmuebles[inmuebles["Tipo"]=="Casa"]["Baños"].min()

inmuebles[inmuebles["Tipo"]=="Casa"][inmuebles[inmuebles["Tipo"]=="Casa"]["Baños"]==0]

"""Casa con mas baños"""

inmuebles[inmuebles["Tipo"]=="Casa"]["Baños"].max()

inmuebles[inmuebles["Tipo"]=="Casa"][inmuebles[inmuebles["Tipo"]=="Casa"]["Baños"]==9]

"""Casa con menos habitaciones"""

inmuebles[inmuebles["Tipo"]=="Casa"]["Habitaciones"].min()

inmuebles[inmuebles["Tipo"]=="Casa"][inmuebles[inmuebles["Tipo"]=="Casa"]["Habitaciones"]==1]

"""Casa con mas habitaciones"""

inmuebles[inmuebles["Tipo"]=="Casa"]["Habitaciones"].max()

inmuebles[inmuebles["Tipo"]=="Casa"][inmuebles[inmuebles["Tipo"]=="Casa"]["Habitaciones"]==110]

"""Resumen estadistico"""

inmuebles.describe()

